version: '3.8'

services:
  sqlite-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: sqlite-api
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/data
    restart: unless-stopped
